GET http://localhost:4020/api/garments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWF0anV0YXByZXR0eSIsImlhdCI6MTY0OTY2MDQ0OCwiZXhwIjoxNjQ5NzQ2ODQ4fQ.AgYAhlMVJa9nJ-PqWiN2X46mKax3fxZPQLi4Pgv1_KQ

###

POST http://localhost:4030/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWF0anV0YXByZXR0eSIsImlhdCI6MTY0OTY2MDQ0OH0.MsT9lTiuwrE_U_Xu1MElhGOfCa7KScNTplmbwAfL8rQ"

}

###

DELETE http://localhost:4030/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWF0anV0YXByZXR0eSIsImlhdCI6MTY0OTY2MDQ0OH0.MsT9lTiuwrE_U_Xu1MElhGOfCa7KScNTplmbwAfL8rQ"

}


###
POST http://localhost:4030/api/login
Content-Type: application/json

{
    "username" : "matjutapretty"
}