GET http://localhost:4018/api/garments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWF0anV0YXByZXR0eSIsImlhdCI6MTY0OTY3NDAwNSwiZXhwIjoxNjQ5NzYwNDA1fQ.ASCD89d8mh5hgRLAtIYRl2WRqxbE5exMsYGffPGg0Go

###

POST http://localhost:4030/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWF0anV0YXByZXR0eSIsImlhdCI6MTY0OTY3NDAwNX0.zmrvXteRAfWA313S4HVvdaxdXAjc4_ipRc7g2HDG6iI"

}

###

DELETE http://localhost:4030/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWF0anV0YXByZXR0eSIsImlhdCI6MTY0OTY3NDAwNX0.zmrvXteRAfWA313S4HVvdaxdXAjc4_ipRc7g2HDG6iI"

}


###
POST http://localhost:4030/api/login
Content-Type: application/json

{
    "username" : "matjutapretty"
}